pr: none
trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: GroupsSyncVars
  - name: TF_VAR_flux_deploy_key_path
    value: $(DEPLOY_KEY)

stages:
  - stage: Download_secure_file
    displayName: Download secure file
    jobs:
      - job: GetFluxDeployKey
        displayName: "Get Flux Deploy Key"
        steps:
          - task: DownloadSecureFile@1
            name: fluxDeployKey
            displayName: "Download Flux Deploy Key"
            inputs:
              secureFile: "fluxDeployKey"

          - script: |
              echo "Updating TF_VAR_flux_deploy_key_path with the secure file path"
              echo "##vso[task.setvariable variable=TF_VAR_flux_deploy_key_path;isOutput=true]$(fluxDeployKey.secureFilePath)"
            name: SetDeployKeyPath
            displayName: "Set Deploy Key Path"

          - script: |
              tree
            name: ShowDirTree
            displayName: "Show dir tree"

  - stage: App_Development_Kubernetes_Services
    displayName: Deploy Development Azure Kubernetes Services
    jobs:
      - template: base_pipeline.yaml
        parameters:
          environment: 'development'
          terragruntDirectory: 'infrastructure-live/app/development/eastus2/aks'
