pr: none
trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: development
  - group: management
    TF_VAR_flux_deploy_key_path: './key'

stages:
  - stage: App_Development_Kubernetes_Services
    displayName: Deploy Development Azure Kubernetes Services
    jobs:
      - job: GetFluxDeployKey
        displayName: "Get Flux Deploy Key"
        steps:
          - task: DownloadSecureFile@1
            name: fluxDeployKey
            displayName: "Download Flux Deploy Key"
            inputs:
              secureFile: "fluxDeployKey"

          - script: |
              echo "Updating TF_VAR_flux_deploy_key_path with the secure file path"
              echo "##vso[task.setvariable variable=TF_VAR_flux_deploy_key_path;isOutput=true]$(fluxDeployKey.secureFilePath)"
            name: SetDeployKeyPath
            displayName: "Set Deploy Key Path"

      - template: ./base-pipeline.yml
        parameters:
          environment: 'development'
          terragruntDirectory: 'infrastructure-live/app/development/eastus2/aks'
