parameters:
  - name: environment
    type: string
  - name: terragruntDirectory
    type: string

jobs:
  - job: TerragruntInitAndPlan
    displayName: Run Terragrunt Init and Terragrunt Plan
    steps:
      - script: |
          echo "Starting Terragrunt init..."
          echo $(TF_VAR_flux_deploy_key_path)
        displayName: "Test variable 1"

      - script: |
          echo "Performing tree..."
          tree
        displayName: "Test variable 2"
